### ISSUE TITLE
cannot load libgstapp-1.0.so.0

### ISSUE THREAD

**Issue by LyzardKing** [diddlesnaps/clouds#1]
Hi!
I installed clouds and started it after adding the necessary plugs.
It downloaded the iso, but now I get the following error after I install:
`/snap/clouds/8/usr/bin/qemu-system-x86_64: error while loading shared libraries: libgstapp-1.0.so.0: cannot open shared object file: No such file or directory`

**Comment by LyzardKing** [comment]
It works if I add libgstreamer-plugins-base1.0-0 to the stage packages

**Comment by diddledan** [comment]
This is now fixed.
