### ISSUE TITLE
Please update store description to remove kvm plug instructions

### ISSUE THREAD

**Issue by mcphail** [diddlesnaps/clouds#6]
The description from `snap info clouds` still contains a stanza about manually connecting the kvm permission, despite this now being automatically set in the store. This caused a bit of confusion for me. That text can be removed. Ta!

**Comment by diddledan** [comment]
Oops. Thank you for pointing this out. I'd completely forgotten I had that text in there :-)

![Gif of clip taken from Clueless with Cher, the lead character played by Alicia Silverstone, saying "My Bad" after hitting another car while driving](https://media0.giphy.com/media/10VJ2YDMoNEBl6/giphy.gif?cid=ecf05e478b8xk6dolnjgrlzcsy79uuwnohw3lczp27dm44jn&rid=giphy.gif)

**Comment by diddledan** [comment]
Closing as fixed.
